name: posh-awsp build
on: [push]
jobs:
  build_test_publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Diagnostics
        run: |
          echo "ref_type: ${{ github.ref_type }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref: ${{ github.ref }}"
      - name: Set up MS repository
        # https://learn.microsoft.com/en-us/powershell/scripting/install/install-ubuntu?view=powershell-7.5
        run: |
          source /etc/os-release
          wget -q https://packages.microsoft.com/config/ubuntu/$VERSION_ID/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
      - name: Install Powershell and .NET
        run: |
          sudo apt-get install -y powershell dotnet-sdk-8.0
      - name: Install Pester
        run: pwsh -Command 'Install-Module -Force -Scope CurrentUser Pester'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: pwsh -File ./build/run-tests.ps1
      - id: get_version
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release/')
        name: Get version
        uses: jannemattila/get-version-from-tag@v4      
      - name: Publish module
        if: github.ref_type == 'tag' && startsWith(github.ref_name, 'release/')
        run: pwsh ./build/publish-module.ps1 -ModuleVersion ${{ github.ref }} -NuGetApiKey ${{ secrets.NUGET_API_KEY }}